### ISSUE TITLE
Consider moving `react-dom` into dependencies

### ISSUE THREAD

**Issue by ctumolosus** [imcnally/react-input-completion#3]
Otherwise it won't be installed when required by another package and your package depends on it, papalote (sorry couldn't resist).

**Comment by victor-castellanos** [comment]
lol :+1:

**Comment by imcnally** [comment]
:grin:

**Comment by imcnally** [comment]
get a pull request up in here

**Comment by imcnally** [comment]
also, wouldn't that make sense as a peerDep?

**Comment by imcnally** [comment]
1.0.1 lists react-dom as a peer dependency :grimacing: 

PAPA-LOTE :clap::clap: ... :clap::clap::clap:
